FORMAT: 1A
HOST: http://itson.apiblueprint.com/

# It's On

"It's On" is a simple API allowing consumers to search for music on different online platforms.
For now only Spotify and Soundcloud are supported.

# Search [/search?term={track_name}]

## Search for a track [GET]
+ Paramenters
    + track_name (required, string, `Moon Eye`) - Track name as a string

+ Response 200 (application/json)

        {
            "results": [
                {
                    "service": "Spotify",
                    "items": [
                        {
                            "urls": {
                                "preview": "https://p.scdn.co/mp3-preview/5e0283c4d837b2c0422dffaabc768c13151a8ce3",
                                "full": "https://open.spotify.com/track/69F5yQfUocXSOkIDBI8qVv"
                            },
                            "album": "Mue",
                            "artists": [
                                "Emilie Simon"
                            ],
                            "title": "The Eye Of The Moon",
                            "type": "track"
                        }
                    ]
                },
                
                {
                    "service": "Soundcloud",
                    "items": [
                    {
                        "urls": {
                            "full": "https://api.soundcloud.com/tracks/205002523"
                        },
                        "artists": [
                            "The O'C Alchemy"
                        ],
                        "title": "Diamonds in the Rough",
                        "type": "track"
                    }]
                }
            ]
        }
